version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-trader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hr4lw0qjdvxw"
s3_prefix = "stock-trader"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
